### ISSUE TITLE
Review homebrew formula

### ISSUE THREAD

**Issue by iwittkau** [jedisct1/piknik#29] opened 2019-12-13 23:04 UTC
Hi, the piknik homebrew formula is currently blocking a pull request to update the go formula to 1.13.5. Details here: https://github.com/Homebrew/homebrew-core/pull/47510#issuecomment-565630208

Can someone take a look at why [the formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/piknik.rb) fails on macOS with go 1.13.5, please?

**Comment by jedisct1** [comment] 2019-12-14 09:54
Piknik works fine with Go 1.13, so there may be something wrong with the test included in the Homebrew formula.

That test just spawns a local server and tries to connect to it. Maybe the issue is actually due to Catalina?
Unfortunately I won’t have a computer for the next few days.

**Comment by iwittkau** [comment] 2019-12-14 22:52
>  Maybe the issue is actually due to Catalina?

No, it failed on High Sierra in the CI pipeline:

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/53405/version=highsierra/testReport/junit/brew-test-bot/high_sierra/test_piknik/

... but it works fine on my MacBook with High Sierra. I'll keep you updated here while you're afk.

**Comment by iwittkau** [comment] 2019-12-15 11:01
With Go 1.13.5 `brew test --verbose piknik` fails on my High Sierra machine.

**Comment by iwittkau** [comment] 2019-12-16 07:34
I think I found a very simple fix to make the tests pass on High Sierra again: https://github.com/Homebrew/homebrew-core/pull/47902

I'll keep this open until Go 1.13.5 is merged.

**Comment by jedisct1** [comment] 2019-12-16 10:41
Sent another PR: https://github.com/Homebrew/homebrew-core/pull/47938

**Comment by jedisct1** [comment] 2019-12-19 16:01
Looks like Go 1.13.5 has been merged :)

**Closed by jedisct1** 2019-12-19 16:01 UTC
